### ISSUE TITLE
Players get VNL upon joining?

### ISSUE THREAD

**Issue by walliski** [walliski/myranks-for-gokz#7]
Sometimes players can be shown to have VNL as rank, even if they are playing some other gamemode. Could it be something that we attempt to set the initial rank too early, before the mode settings have loaded for the player properly?

**Comment by zer0k-z** [comment]
FYI this exists in base GOKZ as well. I suspect that it has something to do with player loading in before client preferences.

**Comment by walliski** [comment]
Aah, good to know! Then I guess its not worth putting time into trying to fix it here 🤔

**Comment by walliski** [comment]
> 
> 
> FYI this exists in base GOKZ as well. I suspect that it has something to do with player loading in before client preferences.

Maybe that is the case. I have now added an additional setting of clan tags also after GOKZ options are loaded. Maybe that works better then...

https://github.com/walliski/myranks-for-gokz/commit/1a72142c96569ea26c115a68e80e14fe29ab473a
